from datetime import datetime
from fastapi import APIRouter
from app.schemas.weather_schemas import WeatherRadarResponse, HourlyForecastPoint

router = APIRouter()

DISTRICT_WEATHER_DB = {
    "tawang": {
        "temp": 14.5,
        "humidity": 94,
        "rainfall_24h": 184.5,
        "intensity": 24.2,
        "soil_sat": 91.5,
        "cloud": 98,
        "wind": 22.0,
        "radar": "IMD Doppler Radar — Mohanbari/Tawang High-Altitude Unit",
        "timeline": [
            {"time_label": "Now", "rainfall_mm": 24.2, "probability_pct": 95, "risk_level": "CRITICAL"},
            {"time_label": "+1h", "rainfall_mm": 21.0, "probability_pct": 90, "risk_level": "CRITICAL"},
            {"time_label": "+2h", "rainfall_mm": 18.5, "probability_pct": 85, "risk_level": "HIGH"},
            {"time_label": "+3h", "rainfall_mm": 14.0, "probability_pct": 75, "risk_level": "HIGH"},
            {"time_label": "+6h", "rainfall_mm": 9.5, "probability_pct": 60, "risk_level": "MODERATE"},
            {"time_label": "+12h", "rainfall_mm": 5.0, "probability_pct": 40, "risk_level": "LOW"},
        ],
    },
    "gangtok": {
        "temp": 17.0,
        "humidity": 88,
        "rainfall_24h": 112.0,
        "intensity": 14.5,
        "soil_sat": 78.5,
        "cloud": 90,
        "wind": 16.5,
        "radar": "IMD Doppler Radar — Gangtok Burtuk Ridge",
        "timeline": [
            {"time_label": "Now", "rainfall_mm": 14.5, "probability_pct": 88, "risk_level": "HIGH"},
            {"time_label": "+1h", "rainfall_mm": 16.0, "probability_pct": 85, "risk_level": "HIGH"},
            {"time_label": "+2h", "rainfall_mm": 12.0, "probability_pct": 80, "risk_level": "HIGH"},
            {"time_label": "+3h", "rainfall_mm": 8.0, "probability_pct": 65, "risk_level": "MODERATE"},
            {"time_label": "+6h", "rainfall_mm": 4.5, "probability_pct": 50, "risk_level": "LOW"},
            {"time_label": "+12h", "rainfall_mm": 2.0, "probability_pct": 30, "risk_level": "LOW"},
        ],
    },
    "shillong": {
        "temp": 16.2,
        "humidity": 92,
        "rainfall_24h": 142.0,
        "intensity": 18.0,
        "soil_sat": 84.0,
        "cloud": 95,
        "wind": 18.0,
        "radar": "IMD Doppler Radar — Sohra / Cherrapunji Weather Observatory",
        "timeline": [
            {"time_label": "Now", "rainfall_mm": 18.0, "probability_pct": 90, "risk_level": "CRITICAL"},
            {"time_label": "+1h", "rainfall_mm": 15.0, "probability_pct": 85, "risk_level": "HIGH"},
            {"time_label": "+2h", "rainfall_mm": 11.5, "probability_pct": 75, "risk_level": "HIGH"},
            {"time_label": "+3h", "rainfall_mm": 7.0, "probability_pct": 60, "risk_level": "MODERATE"},
            {"time_label": "+6h", "rainfall_mm": 4.0, "probability_pct": 45, "risk_level": "LOW"},
            {"time_label": "+12h", "rainfall_mm": 1.5, "probability_pct": 20, "risk_level": "LOW"},
        ],
    },
    "aizawl": {
        "temp": 21.0,
        "humidity": 89,
        "rainfall_24h": 135.0,
        "intensity": 16.5,
        "soil_sat": 82.0,
        "cloud": 92,
        "wind": 14.0,
        "radar": "IMD Doppler Radar — Lengpui Radar Station",
        "timeline": [
            {"time_label": "Now", "rainfall_mm": 16.5, "probability_pct": 88, "risk_level": "HIGH"},
            {"time_label": "+1h", "rainfall_mm": 14.0, "probability_pct": 82, "risk_level": "HIGH"},
            {"time_label": "+2h", "rainfall_mm": 10.0, "probability_pct": 70, "risk_level": "MODERATE"},
            {"time_label": "+3h", "rainfall_mm": 6.5, "probability_pct": 55, "risk_level": "MODERATE"},
            {"time_label": "+6h", "rainfall_mm": 3.0, "probability_pct": 35, "risk_level": "LOW"},
            {"time_label": "+12h", "rainfall_mm": 1.0, "probability_pct": 20, "risk_level": "LOW"},
        ],
    },
    "kohima": {
        "temp": 18.0,
        "humidity": 86,
        "rainfall_24h": 95.0,
        "intensity": 11.0,
        "soil_sat": 76.0,
        "cloud": 85,
        "wind": 12.0,
        "radar": "IMD Doppler Radar — Kohima Hillside Telemetry Unit",
        "timeline": [
            {"time_label": "Now", "rainfall_mm": 11.0, "probability_pct": 80, "risk_level": "HIGH"},
            {"time_label": "+1h", "rainfall_mm": 9.5, "probability_pct": 75, "risk_level": "MODERATE"},
            {"time_label": "+2h", "rainfall_mm": 7.0, "probability_pct": 60, "risk_level": "MODERATE"},
            {"time_label": "+3h", "rainfall_mm": 4.5, "probability_pct": 45, "risk_level": "LOW"},
            {"time_label": "+6h", "rainfall_mm": 2.0, "probability_pct": 30, "risk_level": "LOW"},
            {"time_label": "+12h", "rainfall_mm": 0.5, "probability_pct": 15, "risk_level": "LOW"},
        ],
    },
    "imphal": {
        "temp": 23.0,
        "humidity": 78,
        "rainfall_24h": 65.0,
        "intensity": 8.0,
        "soil_sat": 62.0,
        "cloud": 70,
        "wind": 10.0,
        "radar": "IMD Doppler Radar — Imphal Tulihal Station",
        "timeline": [
            {"time_label": "Now", "rainfall_mm": 8.0, "probability_pct": 65, "risk_level": "MODERATE"},
            {"time_label": "+1h", "rainfall_mm": 6.0, "probability_pct": 55, "risk_level": "MODERATE"},
            {"time_label": "+2h", "rainfall_mm": 4.0, "probability_pct": 40, "risk_level": "LOW"},
            {"time_label": "+3h", "rainfall_mm": 2.0, "probability_pct": 30, "risk_level": "LOW"},
            {"time_label": "+6h", "rainfall_mm": 1.0, "probability_pct": 20, "risk_level": "LOW"},
            {"time_label": "+12h", "rainfall_mm": 0.0, "probability_pct": 10, "risk_level": "LOW"},
        ],
    },
    "guwahati": {
        "temp": 28.0,
        "humidity": 72,
        "rainfall_24h": 45.0,
        "intensity": 5.0,
        "soil_sat": 54.0,
        "cloud": 60,
        "wind": 8.0,
        "radar": "IMD Doppler Radar — Borjhar Guwahati Observatory",
        "timeline": [
            {"time_label": "Now", "rainfall_mm": 5.0, "probability_pct": 50, "risk_level": "MODERATE"},
            {"time_label": "+1h", "rainfall_mm": 3.5, "probability_pct": 40, "risk_level": "LOW"},
            {"time_label": "+2h", "rainfall_mm": 2.0, "probability_pct": 30, "risk_level": "LOW"},
            {"time_label": "+3h", "rainfall_mm": 1.0, "probability_pct": 20, "risk_level": "LOW"},
            {"time_label": "+6h", "rainfall_mm": 0.0, "probability_pct": 15, "risk_level": "LOW"},
            {"time_label": "+12h", "rainfall_mm": 0.0, "probability_pct": 10, "risk_level": "LOW"},
        ],
    },
    "agartala": {
        "temp": 29.5,
        "humidity": 68,
        "rainfall_24h": 28.0,
        "intensity": 3.0,
        "soil_sat": 42.0,
        "cloud": 45,
        "wind": 7.0,
        "radar": "IMD Doppler Radar — Agartala Singerbhil Unit",
        "timeline": [
            {"time_label": "Now", "rainfall_mm": 3.0, "probability_pct": 35, "risk_level": "LOW"},
            {"time_label": "+1h", "rainfall_mm": 2.0, "probability_pct": 25, "risk_level": "LOW"},
            {"time_label": "+2h", "rainfall_mm": 1.0, "probability_pct": 20, "risk_level": "LOW"},
            {"time_label": "+3h", "rainfall_mm": 0.5, "probability_pct": 15, "risk_level": "LOW"},
            {"time_label": "+6h", "rainfall_mm": 0.0, "probability_pct": 10, "risk_level": "LOW"},
            {"time_label": "+12h", "rainfall_mm": 0.0, "probability_pct": 5, "risk_level": "LOW"},
        ],
    },
}

@router.get("/radar/{district}", response_model=WeatherRadarResponse, summary="Get Live IMD Weather Radar & 12h Rain Forecast")
async def get_weather_radar(district: str):
    key = district.lower().strip()
    data = DISTRICT_WEATHER_DB.get(key, DISTRICT_WEATHER_DB["tawang"])
    
    return WeatherRadarResponse(
        district=district.capitalize(),
        state="North Eastern Region",
        current_temp_c=data["temp"],
        humidity_pct=data["humidity"],
        rainfall_accumulated_24h_mm=data["rainfall_24h"],
        rainfall_intensity_mm_hr=data["intensity"],
        soil_saturation_pct=data["soil_sat"],
        cloud_cover_pct=data["cloud"],
        wind_speed_kmh=data["wind"],
        forecast_timeline=[HourlyForecastPoint(**pt) for pt in data["timeline"]],
        imd_radar_station=data["radar"],
        last_updated=datetime.now().strftime("%Y-%m-%d %H:%M:%S IST"),
    )
